modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${license}"
issueTrackerURL="${issue_tracker}"

[[mods]]
  modId="${modid}"
  displayName="${display_name}"
  description="${description}"
  version="${version}"
  displayURL="${display_url}"
  updateJSONURL="${update_url}"
  authors="${authors}"
  credits="${credits}"
  logoFile="${logo_file}"

[[dependencies.tcintegrations]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.tcintegrations]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.tcintegrations]]
    modId="tconstruct"
    mandatory=true
    versionRange="${tic_version_range}"
    ordering="AFTER"
    side="BOTH"
[[dependencies.tcintegrations]]
    modId="immersiveengineering"
    mandatory=false
    versionRange="[0,]"
    ordering="AFTER"
    side="BOTH"
[[dependencies.tcintegrations]]
    modId="botania"
    mandatory=false
    versionRange="[0,]"
    ordering="AFTER"
    side="BOTH"
[[dependencies.tcintegrations]]
    modId="aquaculture"
    mandatory=false
    versionRange="[0,]"
    ordering="AFTER"
    side="BOTH"
[[dependencies.tcintegrations]]
    modId="malum"
    mandatory=false
    versionRange="[${malum_minimum_version},]"
    ordering="NONE"
    side="BOTH"
[[dependencies.tcintegrations]]
    modId="create"
    mandatory=false
    versionRange="[${create_min_version},]"
    ordering="NONE"
    side="BOTH"
