modLoader="javafml"
loaderVersion="${loader_version_range}"
license="MIT"
issueTrackerURL="https://github.com/wendall911/TCIntegrations/issues"

[[mods]]
  modId="tcintegrations"
  displayName="Tinkers' Integrations and Tweaks"
  description="Tinkers' Construct Mod Integraions and Tweaks."
  version="${version}"
  displayURL="https://github.com/wendall911/TCIntegrations"
  updateJSONURL="https://raw.githubusercontent.com/wendall911/TCIntegrations/1.18.2/files/updates.json"
  authors="wendall911"
  credits="ashar42"
  logoFile="logo.png"

[[dependencies.tcintegrations]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.tcintegrations]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.tcintegrations]]
    modId="tconstruct"
    mandatory=true
    versionRange="[0,]"
    ordering="AFTER"
    side="BOTH"
[[dependencies.tcintegrations]]
    modId="immersiveengineering"
    mandatory=false
    versionRange="[0,]"
    ordering="AFTER"
    side="BOTH"
[[dependencies.tcintegrations]]
    modId="botania"
    mandatory=false
    versionRange="[0,]"
    ordering="AFTER"
    side="BOTH"
[[dependencies.tcintegrations]]
    modId="aquaculture"
    mandatory=false
    versionRange="[0,]"
    ordering="AFTER"
    side="BOTH"
[[dependencies.tcintegrations]]
    modId="malum"
    mandatory=false
    versionRange="[${malum_minimum_version},]"
    ordering="NONE"
    side="BOTH"
